### ISSUE TITLE
Is there any way of running this docker without network=host?

### ISSUE THREAD

**Issue by Gronis** [joch/deconz-docker#2]
Hi!

Nice to finally get a docker container that works for deconz using x86 hardware!

I would like to run the container using a bridged network between home-assistant and deconz, rather than using network=host on the deconz container. I kind of get it working, except network updates are not pushed to home-assistant when the state of devices are changed on my zigbee network, when I do not use network=host on the deconz image. Any idea if and how to get that working using this image?

This is by docker-compose.yaml
```yaml
  deconz:
    container_name: deconz
    hostname: deconz
    image: joch/deconz
    restart: always
    environment:
      - TZ="Europe/Stockholm"
    ports:
      - "8080:8080"
#   network_mode: host -- when enabled, this works, but then I cannot use my home_automation network
    networks: # -- When using 'network_mode: host', this network cannot be used
      - home_automation
    volumes:
      - .deconz:/root/.local/share/dresden-elektronik/deCONZ:rw
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

**Comment by joch** [comment]
Are you using discovery in HA, or manually setting the IP to deconz? Setting it manually may help!

**Comment by Gronis** [comment]
Yes, I set it manually in the config like this: 
```yaml
deconz:
  host: 192.168.1.102
  port: 8080
```
Maybe I have to stick with `network_mode: host`.
